spring:
  application:
    name: springweb

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springweb
    username: root
    password: 612520
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



  session:
    store-type: jdbc


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  address: 0.0.0.0
  servlet:
    session:
      timeout: 30m